GTBitsOfGood/hope-for-haiti

src/app/account_management/page.tsx
src/app/distributions/page.tsx
src/app/donor_offers/page.tsx
src/app/map/page.tsx
src/app/page.tsx
src/app/profile/page.tsx
src/app/sign_in/page.tsx
src/app/unallocated_items/page.tsx
src/app/wishlist/page.tsx
src/app/wishlists/page.tsx

Disable dynamic routes

---

src/app/api/users/route.test.ts
src/app/api/users/route.ts

Added list users query route handler

---

package-lock.json
package.json
src/components/NavBarLayout.tsx
src/screens/SignInScreen.tsx
tailwind.config.ts

finished login page design

---

src/app/api/unclaimedItems/route.test.ts
src/app/api/unclaimedItems/route.ts
src/test/util/dbMockUtils.ts

updated list unclaimed items query (with date filtering)

---

src/app/api/invites/route.test.ts
src/app/api/invites/route.ts
src/app/api/partnerDetails/[userId]/route.ts
src/schema/partnerDetails.ts

Resolves #20 
Also fixes partner details schema. The custom conditions were returning true values on error, but [should be returning false values on error ](https://zod.dev/?id=refine) so I negated all custom conditions.

Add partner details to user invite

---

src/app/api/partners/route.test.ts
src/app/api/partners/route.ts

created list partners route handler + tests

---

src/app/api/items/route.test.ts
src/app/api/items/route.ts

create item mutation + tests

---

src/app/api/unallocatedItems/route.test.ts
src/app/api/unallocatedItems/route.ts

Replace ID with unallocated item group attributes

---

package-lock.json
src/app/api/items/bulk/route.test.ts
src/app/api/items/bulk/route.ts

Create a `POST` route handler at `/api/items/bulk` that accepts a JSON body and creates multiple `Item` records using the POST'ed data. The JSON body is an array of `Item` objects. Every column will be present on the JSON body.

Created the normal POST function and basic test for authorization

---

src/app/api/unclaimedItems/route.test.ts
src/app/api/unclaimedItems/route.ts

Resolves #45
- I was not able to get the "@/test/realDb" to work. When I used it, changes to the database persisted between tests.  For now, I just have a beforeEach that clears and seeds the db before each of the tests

Group items and filter by visibility

---

src/screens/PartnerProfilePageTabs/ContactInformation.tsx
src/screens/PartnerProfilePageTabs/FacilityInformation.tsx
src/screens/PartnerProfilePageTabs/Finances.tsx
src/screens/PartnerProfilePageTabs/GeneralInfo.tsx
src/screens/PartnerProfilePageTabs/InfrastructureServices.tsx
src/screens/PartnerProfilePageTabs/Introduction.tsx
src/screens/PartnerProfilePageTabs/ProgramServices.tsx
src/screens/PartnerProfilePageTabs/StaffInformation.tsx
src/screens/ProfileScreen.tsx
src/screens/ProfileScreenPartner.tsx
src/screens/ProfileScreenStaff.tsx

staff profile page with all tabs

---

src/screens/PartnerProfilePageTabs/ContactInformation.tsx
src/screens/PartnerProfilePageTabs/FacilityInformation.tsx
src/screens/PartnerProfilePageTabs/Finances.tsx
src/screens/PartnerProfilePageTabs/GeneralInfo.tsx
src/screens/PartnerProfilePageTabs/InfrastructureServices.tsx
src/screens/PartnerProfilePageTabs/Introduction.tsx
src/screens/PartnerProfilePageTabs/ProgramServices.tsx
src/screens/PartnerProfilePageTabs/StaffInformation.tsx
src/screens/ProfileScreen.tsx

partner profile page with all tabs

---

src/screens/UnallocatedItemsScreen.tsx
tailwind.config.ts

unallocated items partner view

---

package-lock.json
package.json
src/app/api/donorOffers/[donorOfferId]/route.test.ts
src/app/api/donorOffers/[donorOfferId]/route.ts
src/app/api/donorOffers/[donorOfferId]/types.ts
src/app/api/donorOffers/route.test.ts
src/app/api/donorOffers/route.ts
src/app/api/donorOffers/types.ts
src/app/donorOffers/[donorOfferId]/page.tsx
src/app/donorOffers/page.tsx
src/screens/DonorOffersScreen.tsx
src/screens/DonorOffersScreens/DonorOffersScreen.tsx
src/screens/DonorOffersScreens/DynamicDonorOfferScreen.tsx
src/screens/DonorOffersScreens/PartnerDonorOffersScreen.tsx
src/screens/DonorOffersScreens/PartnerDynamicDonorOfferScreen.tsx

**`GET /api/donorOffers`**
```json
[
{ "donorOfferId": 5, "offerName": "Offer 1", "donorName": "Org 1", "responseDeadline": "12/2/2025", "state": "RESPONSE_SUBMITTED" },
]
```
**`/GET /api/donorOffers/[donorOfferId]`**
```json
{
"donorOfferName": "Offer 1",
"donorOfferItemsRequests": [
{ "requestId": 24, "title": "title 1", "type": "chicken", "expiration": "12/04/2025", "quantity": 44, "unitSize": "32oz", "quantityRequested": 20, "comments": "comments 1", "priority": "MEDIUM"},
],
}
```
There are minor bugs in the pages, I have listed them at the top of each respective file.
**Frontend (`/donorOffers`)**
**Frontend (`/donorOffers/[donorOfferId]`)**

Finished Backend for ticket [strong]

---

src/app/api/unallocatedItems/lineItems/route.test.ts
src/app/api/unallocatedItems/lineItems/route.ts
src/app/api/unallocatedItems/route.ts
src/app/unallocatedItems/lineItems/page.tsx
src/screens/UnallocatedItemsLineItemsScreen.tsx
src/util/util.ts

View Unique Line Items Page 

---

prisma/migrations/20250405213410_add_unit_type/migration.sql
prisma/schema.prisma
src/app/api/unallocatedItemRequest/route.ts
src/screens/PartnerUnallocatedItemsScreen.tsx
src/screens/PartnerUnallocatedItemsScreens/MyRequests.tsx
src/screens/PartnerUnallocatedItemsScreens/UnallocatedItems.tsx

Implement request creation and viewing

---

src/app/api/distributions/[signOffId]/route.ts
src/app/api/distributions/[signOffId]/types.ts
src/app/api/distributions/route.get.test.ts
src/app/api/distributions/route.ts
src/app/api/distributions/types.ts
src/app/distributions/view/[signOffId]/page.tsx
src/screens/PartnerDistributionsScreenTables/CompleteTable.tsx
src/screens/PartnerDistributionsScreenTables/InProgressTable.tsx
src/screens/PartnerDistributionsScreenTables/ShipmentStatusLabel.tsx
src/screens/PartnerDistributionsScreenTables/ViewDistributionsOfSignOffScreen/PartnerSignOffScreen.tsx
src/screens/PartnerDistributionsScreenTables/ViewDistributionsOfSignOffScreen/TableOfItemsOfDistributions.tsx

Resolves partner distributions page flow.
THE SEARCH BAR doesn't have any functionality.

Partner distribution page flows, no search bar feature added

---

src/screens/AdminUnallocatedItemsScreen.tsx

Filtering works, selects all if no tab selected

---

src/app/api/donorOffers/[donorOfferId]/finalize/route.ts
src/app/api/donorOffers/create/route.ts
src/app/api/partners/route.ts
src/app/donorOffers/[donorOfferId]/finalize/page.tsx
src/app/donorOffers/create/page.tsx
src/components/BulkAdd/BulkAddTable.tsx
src/components/DonorOffers/DonorOfferErrorModal.tsx
src/components/DonorOffers/DonorOfferSuccessModal.tsx
src/components/DonorOffers/ErrorDisplay.tsx
src/components/DonorOffers/FileInfoDisplay.tsx
src/components/DonorOffers/PartnerSearch.tsx
src/components/DonorOffers/PreviewTable.tsx
src/components/DonorOffers/index.ts
src/components/FileUpload.tsx
src/screens/BulkAddItemsScreen.tsx
src/screens/DonorOffersScreens/CreateDonorOfferScreen.tsx
src/screens/DonorOffersScreens/FinalizeDonorOfferScreen.tsx

Rishab paruchuri/donor offer pages

---

src/components/EditAllocationModal.tsx
src/components/NewAllocationModal.tsx

renamed confirmation buttons on allocation modal
Resolves #110

Renamed confirmation buttons on allocation modal

---

src/components/AddItemModal.tsx
src/components/EditAllocationModal.tsx
src/components/NewAllocationModal.tsx
src/components/ShippingItemsModal.tsx
src/screens/AddItemToDistributionScreen.tsx
src/screens/AdminDistributionsScreen/DistributionTable.tsx
src/screens/DonorOfferLineItemsScreen.tsx
src/screens/UnallocatedItemsLineItemsScreen.tsx

Changed pallet number to pallet in UI

---

package-lock.json
package.json
prisma/migrations/20250407063913_update_sign_off_fields/migration.sql
prisma/schema.prisma
src/app/api/distributions/admin/route.ts
src/app/api/distributions/route.ts
src/screens/AdminDistributionsScreen/CreateSignOffScreen/CreateSignOff.tsx
src/screens/AdminDistributionsScreen/CreateSignOffScreen/CreateSignOffTable.tsx
src/screens/AdminDistributionsScreen/CreateSignOffScreen/FinalSignOff.tsx
src/screens/AdminDistributionsScreen/CreateSignOffScreen/SignatureModal.tsx
src/screens/AdminDistributionsScreen/HiddenItems.tsx
src/screens/AdminDistributionsScreen/SignOffs.tsx

Setup Signature Page

---

src/components/AddItemModal.tsx

Update GIK description

---

src/screens/PartnerDistributionsScreen.tsx
src/screens/PartnerDistributionsScreenTables/ViewDistributionsOfSignOffScreen/PartnerSignOffScreen.tsx

fixed note on partner distribution page

---

src/components/NavBarLayout.tsx

update nav bar

---

src/components/StatusTag.tsx
src/screens/DonorOfferLineItemsScreen.tsx
src/screens/UnallocatedItemsLineItemsScreen.tsx

update unique line items page

---

src/components/PriorityTag.tsx
src/components/StatusTag.tsx
src/screens/DonorOfferLineItemsScreen.tsx
src/screens/DonorOffersScreens/AdminDynamicDonorOfferScreen.tsx
src/screens/PartnerRequestsScreen.tsx
src/screens/PartnerUnallocatedItemsScreens/MyRequests.tsx
src/screens/PartnerUnallocatedItemsScreens/UnallocatedItems.tsx
src/screens/UnallocatedItemsLineItemsScreen.tsx

Update design of partner unallocated items screen

---

.prettierrc
src/app/api/unallocatedItems/route.ts
src/screens/PartnerUnallocatedItemsScreens/UnallocatedItems.tsx

Fix Unallocated Items Request Column

---

src/screens/AdminUnallocatedItemsScreen.tsx

added all tab to admin unallocated items

---

src/app/api/unallocatedItemRequest/route.ts
src/app/api/updateUnallocatedItemRequest/route.ts
src/components/ModalDropDown.tsx
src/components/ModalTextField.tsx
src/screens/PartnerUnallocatedItemsScreens/MyRequestCommentModal.tsx
src/screens/PartnerUnallocatedItemsScreens/MyRequests.tsx
src/screens/PartnerUnallocatedItemsScreens/UnallocatedItems.tsx

Add Editable Request Items

---

src/app/api/donorOffers/route.ts
src/screens/DonorOffersScreens/PartnerDonorOffersScreen.tsx

Fix Status Donor Offer

---

src/components/BulkAdd/BulkAddTable.tsx

update bulk add item table headers and visible,allowed identifiers

---

src/components/UnallocatedItems/EditUniqueLineItem.tsx
src/screens/UnallocatedItemsLineItemsScreen.tsx

Resolves #131  (not more like half of it)

part of the line items ui

---

src/app/api/distributions/admin/route.ts
src/app/api/donorOffers/[donorOfferId]/edit/route.ts
src/app/api/donorOffers/[donorOfferId]/route.ts
src/app/api/donorOffers/items/[itemId]/lineItems/route.ts
src/app/api/donorOffers/items/[itemId]/requests/route.ts
src/app/api/donorOffers/route.ts
src/app/api/items/route.ts
src/app/api/shippingStatus/[partnerId]/route.ts
src/app/api/signOffs/[partnerId]/route.ts
src/app/api/unallocatedItemRequest/route.ts
src/app/api/unallocatedItemRequests/route.ts
src/app/api/unallocatedItems/lineItems/route.ts
src/app/api/unallocatedItems/route.ts
src/app/api/users/route.ts
src/schema/tableParams.ts
src/services/distributionService.ts
src/services/donorOfferService.ts
src/services/itemService.ts
src/services/shippingStatusService.ts
src/services/signOffService.ts
src/services/unallocatedItemService.ts
src/services/userService.ts
src/types/api/distribution.types.ts
src/types/api/donorOffer.types.ts
src/types/api/filter.types.ts
src/types/api/shippingStatus.types.ts
src/types/api/signOff.types.ts
src/util/table.ts

Backend Table Query Standardization
